### ISSUE TITLE
Resync Theia Manager at startup

### ISSUE THREAD

**Issue by salv-orlando** [antrea-io/theia#135]
If the Theia manager is restarted due to events such as errors, evacuation or user actions we must make sure it synchronizes with the latest state with both Clickhouse and Spark.

From a scale perspective, we should ensure this synchronization does not add significant time to startup processes when there is a large data set to validate.

**Comment by yanjunz97** [comment]
All Team, I list the workflow for the resynchronization as follows. Basically we need to take care of two resources.

SparkApplication:

- Creation: Add label `app=network-policy-recommendation` when creating SparkApplication in controller
- Resynchronization
  - List all the SparkApplication with the label
  - Find corresponding NetworkPolicyRecommendation for each SparkApplication id
  - Delete SparkApplication without a matching NetworkPolicyRecommendation

ClickHouse entry:

- Retrieve all distinct id from recommendations table
- Find corresponding NetworkPolicyRecommendation for each id
- Delete table entry without a matching NetworkPolicyRecommendation

I think we can put the resynchronization in a Goroutine in the controller's Run() function. From the race condition perspective, as

- Both SparkApplication and ClickHouse entry are safe to be deleted multiple times(which may happen when users try to delete NPR during the Resync)
- On creation, NPR is always created before SparkApplication and ClickHouse entry. Thus the Resync process will not delete resources of new NPR created after the startup of the controller

I do not think of any concern. Appreciate any suggestion about the strategy!

**Comment by wsquan171** [comment]
> Add label app=network-policy-recommendation

Maybe use some thiea / antrea prefix for the label? Probably also requires abbreviating npr part.

> Delete table entry without a matching NetworkPolicyRecommendation

Do we want to batch these deletions?

> put the resynchronization in a Goroutine in the controller's Run() function.

Will this be run only once for each controller start? I'm thinking that in case of NPR crd deletion failure (crd removed but left over spark application or db entry), does our code currently able to clean the rest up in a retry?
