### ISSUE TITLE
Network Threat Analytics - Throughput Anomaly Detector

### ISSUE THREAD

**Issue by salv-orlando** [antrea-io/theia#149]
Detect throughput anomalies in Antrea flows using well-known algorithms.
The feature should be able to do detection for individual flows, or for a given pod traffic (source and destination)

The feature should provide:
- Spark Application for Network Flow Analysis
- Theia manager integration
- CLI support

**Comment by dreamtalen** [comment]
Append next steps in v0.6 release after PR #152 merged:

1. Expand the scope of throughput anomaly detection beyond each endpoint-to-endpoint flow, for example:
    - Monitor the aggregated in/out throughput of a given Pod
    - Monitor the aggregated in/out throughput of a Pod sets (Pod label)
    - Monitor the aggregated in/out throughput of a given Service
2. Develop CLI commands and Theia manager integration for the Spark Streaming version job: https://github.com/antrea-io/theia/blob/b1bcc1a2b48b1d2617afbd6f5fca53ac716f08f5/plugins/anomaly-detection/SparkStreaming.py
