### ISSUE TITLE
Create a unified docker image for all Spark applications

### ISSUE THREAD

**Issue by dreamtalen** [antrea-io/theia#161]
All of our Spark applications, including Policy Recommendation and Throughput Anomaly Detection, are built on the `gcr.io/spark-operator/spark-py` docker image and have their dependent libraries installed on top. 

However, this image has a relatively large size of around 1GB. To save disk space on the user's node and prepare for the addition of more Spark applications in the future, we aim to create a unified docker image for all of these applications.

**Comment by tushartathgur** [comment]
Also restructure spark and other common constants from both TAD  and NPR controllers to utils.go

**Comment by tushartathgur** [comment]
Code merged!
