### ISSUE TITLE
Add an operator for ClickHouse uninstallation

### ISSUE THREAD

**Issue by yanjunz97** [antrea-io/theia#162]
The ClickHouse cluster needs ZooKeeper for deletion. But when uninstalling Theia with yaml file or Helm chart as a whole, Zookeeper is always deleted before ClickHouse. This will lead to a fact that ClickHouse deletion will be stuck, while the ClickHouse Operator will keep trying to connect ZooKeeper for around 4 minutes and eventually fail.

Currently we instruct the user in [doc](https://github.com/antrea-io/theia/blob/main/docs/network-flow-visibility.md#clickhouse-cluster) to manually delete the ClickHouse first and then uninstall the rest of Theia. But for usability, we need an operator to take care of the installation and uninstallation order of ClickHouse cluster and ZooKeeper.

**Comment by tushartathgur** [comment]
In Theia, we are leveraging ClickHouse-Keeper which will help us be on track with the new developments from ClickHouse.
we shall also be adding an upgrade script that helps users to upgrade seamlessly from zookeeper to ClickHouse-keeper without losing the data.
