### ISSUE TITLE
User-friendly names for flow record fields in Grafana dashboard

### ISSUE THREAD

**Issue by heanlan** [antrea-io/theia#76]
Issue description: Names for columns and filters are exactly the ones returned by queries
Improvement: Have friendly names for columns used in tables and filters. For instance "flowEndSecondsFromSourceNode" could be displayed as "end of flow as reported by source"

**Comment by yuntanghsu** [comment]
| Before  | After |
| ------------- | ------------- |
| timeInserted  | time when flow inserted to ClickHouse  |
| flowStartSeconds  | start time of flow  |
| | |
| | |
| | |
| | |
